doctrine:
    dbal:
        types:
            uuid_binary_ordered_time: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
            uuid_binary:  Ramsey\Uuid\Doctrine\UuidBinaryType
            uuid: Ramsey\Uuid\Doctrine\UuidType
        mapping_types:
            uuid_binary_ordered_time: guid
            uuid_binary: guid
            _text: string

